### ISSUE TITLE
Fix your typo

### ISSUE THREAD

**Issue by Nerdmaster** [pymander/prime-json-service#1]
I was showing this to my boss and a few others, trying to present this service as a viable enterprise initiative project within the customer-focus infrastructure, and hit the following URL: http://1.sigma-crow-364.appspot.com/prime?number=43253425342514314321543154325234143214321423153425234&sumbit=Go

The marketing folks just loved seeing "sumbit".  Not only did my proposal get rejected, but I've been asked to pack up my things and leave.

The error can be found here: https://github.com/pymander/prime-json-service/blob/master/prime/templates/index.html#L21

I'd offer a pull request, but I need to go hit the classifieds and find a new job.

**Comment by pymander** [comment]
This was the most useful bug report in the entire universe. Let me know which bridge you end up living under, so I can bring you some old bread.
